### ISSUE TITLE
Is it really needed to change the permission to read-only?

### ISSUE THREAD

**Issue by tkoksg** [rened/DeclarativePackages.jl#5] opened 2015-10-07 01:25 UTC
Thank you for making very useful package!
I think this kind of package management tool is needed for Julia.

I had a problem when using a package declaration with commit hash specified like:
```
DataFrames 0.6.9
# 0.1.0 master
https://github.com/antinucleon/XGBoost.jl.git 23b883ce17b630c18ad2f1ae5d0fe8352ecc4d3f
```

causing an error raised at src/DeclarativePackages.jl
```
if pkg != "METADATA" && isdirty
            error("$status -- Cannot create a jdp declaration from the currently installed packages as '$pkg' has local changes.\nPlease commit these changes, then run 'jdp' again.")
        end
```

I dug into the package directory and found that the only change was the permission such as:
```
old mode 100644
new mode 100755
```
Assuming that this is caused by the permission change part in /installpackages.jl,  I am currently using DeclarativePackages commenting out that part,  but I'm not sure this is the right way.

**Comment by rened** [comment] 2015-10-07 04:06
Hi, thanks a lot for reporting this - I will look into it!

**Comment by rened** [comment] 2015-10-07 04:32
@tkoksg, could you please post your `versioninfo()`?  Your `DECLARE` snippet works for me on Ubuntu 14.04 with Julia 0.4.

On OSX a `Pkg.add("XGBoost")` fails for me with and without DeclarativePackages. The error you mention is not thrown in this case, the error occurs during the build phase of XGBoost, something about a missing wrapper.

**Comment by tkoksg** [comment] 2015-10-07 04:46
Actually, it seems that this error occurs when I run
```
cp DECLARE.min DECLARE; jdp
```
for the second time (where DECLARE.min is specified as the first report)

```
julia> versioninfo()
Julia Version 0.4.0-rc4
Commit e9c9c92* (2015-10-04 03:14 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by rened** [comment] 2015-10-07 07:14
Ah, the `cp DECLARE.min DECLARE; jdp` was important - I can reproduce it now, and just pushed a fix. I only make the top-most dir read-only now.

Could you please `Pkg.checkout("DeclarativePackages")` and see whether it works?

**Comment by tkoksg** [comment] 2015-10-07 07:53
Tried but failed. The change is not yet commited?

**Comment by rened** [comment] 2015-10-07 07:58
uh, sorry, the commit is pushed now...

**Comment by tkoksg** [comment] 2015-10-07 08:05
It works now for me too. Thanks.

**Comment by rened** [comment] 2015-10-07 08:06
Great! Thanks again for reporting this!

**Comment by tkoksg** [comment] 2015-10-07 08:21
Sorry for bothering you again.
I continued to develop my project but encountered a new error after the checkout. Is this related to the change?

```
julia> using DataFrames
INFO: Precompiling module DataFrames...
ERROR: SystemError: mkdir: Permission denied
 in mkdir at file.jl:42
 in mkpath at file.jl:50
 in mkpath at file.jl:49
 in mkpath at file.jl:46
 in compilecache at loading.jl:379
 in require at ./loading.jl:250
```

**Comment by rened** [comment] 2015-10-07 08:30
No problem! Let me look into this. It seems that the precompilation needs access to the package's dir, although it is not clear to me why.

**Comment by rened** [comment] 2015-10-07 08:58
Could you please run `Pkg.checkout("DeclarativePackages")` again? Should be fixed now.

**Comment by tkoksg** [comment] 2015-10-07 09:31
It worked fine. Thanks again!

**Comment by rened** [comment] 2015-10-07 09:32
Cool! Thanks for your feedback!

**Closed by rened** 2015-10-07 09:32 UTC
